[package]
name = "speakiput-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
native-capture = ["dep:cpal"]

[dependencies]
async-trait.workspace = true
cpal = { workspace = true, optional = true }
hound.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
