[package]
name = "speakiput-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
speakiput-client = { path = "../speakiput-client" }
speakiput-contract = { path = "../speakiput-contract" }
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true

[[bin]]
name = "speakiput-conformance"
path = "src/bin/conformance.rs"

